# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Start Jekyll
email: funnyyoushouldmentionthat@gmail.com	
description: >
  A guide to getting started with Jekyll.
baseurl: "/startjekyll.git"
url: "http://criticaltom.github.io"
twitter_username: critical_tom
github_username:  N/A

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
